---
- name: Install and start Apache HTTPD
  hosts: all
  gather_facts: false
  tasks:
    - name: 1) httpd package is present
      yum:
        name: httpd
        state: present

    - name: Correct index.html is present
      copy:
        content: "Welcome to My Server.\n"
        dest: /var/www/html/index.html
        mode: '0644'

    - name: httpd is started
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld

    - name: Configuration firewall
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

