---
- name: unins
  hosts: all
  gather_facts: false
  tasks:
    - name: 1) httpd package is present
      yum:
        name: httpd
        state: absent

    - name: Correct index.html is present
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: Configuration firewall
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled

    - name: httpd is started
      service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - httpd
        - firewalld