---
- name: unins
  hosts: webserver
  tasks:
    - name: Open the service with firewall
      firewalld:
        service: "{{ ansible_local.custom.general.fwsvc }}"
        permanent: true
        immediate: true
        state: disabled
    - name: Start the service
      service:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - "{{ ansible_local.custom.general.service }}"
        - firewalld
    - name: Install the required package
      yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: absent
    - name: 333333일 삭제 - (file) /var/www/html/index.html
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: absent
