---
- name: restore
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - vars/secret.yml
  tasks:
    - name: dele
      user:
        name: "{{ item.name }}"
        state: absent
        remove: true
      loop: "{{ newusers }}"
