---
#############################3
# 1) 서비스 패키지 설치 - mariadb-server, httpd
# 2) 서비스 기동 - mariadb, httpd
#############
- name: 1) 서비스 패키지 설치 - mariadb-server, httpd
  ansible.builtin.dnf:
    name:
      - "{{ ansible_local.custom.packages.db_package }}"
      - "{{ ansible_local.custom.packages.web_package }}"
    state: present

- name: 2) 서비스 기동 - mariadb, httpd
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - "{{ ansible_local.custom.services.db_service }}"
    - "{{ ansible_local.custom.services.web_service }}"
    