---
- name: 0) 복구
  hosts: web1.example.com
  tasks:
    ##############################
    # 1) 방화벽 삭제 - http
    # 2) 웹서비스 중지 - httpd.service
    # 3) 웹서버 삭제 - /var/www/html/index.html
    # 4) 패키지 삭제 - httpd
    ######################
    - name: 1) f r
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled

    - name: 2) sys stop
      ansible.builtin.systemd:
        state: stopped
        name: httpd
        enabled: false

    - name: 3) file
      ansible.builtin.file:
          path: /var/www/html/index.html
          state: absent

    - name: 4) dnf rem      
      ansible.builtin.yum:
          name: httpd
          state: absent
          
