---
- name: Play 01 파일 서버 패키지 설치
  hosts: all
  tasks:
    - name: 1) 변수 포함 - package.yml
      include_vars: restore_package.yml

    - name: 2) 패키지 설치 - httpd
      include_tasks: uninstall_package.yml

