---
- name: 0) 324
  hosts: all
  remote_user: ansible
  become: true
  vars_files:
    - vars/useradd.yml
  tasks:
    - name: 1) 34
      ansible.builtin.user:
        name: "{{  item.id }}"
        password: "{{ item.pw | password_hash('sha512') }}"
      loop: "{{ newuser }}"

    - name: 3) SSH Public Key 배포
      ansible.posix.authorized_key:
        user: developer
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

    - name: Deploy file
      copy: 
        src: files/developer
        dest: /etc/sudoers.d/developer
        owner: root
        group: root
        mode: '0440'


- name: 0) 222
  hosts: all
  gather_facts: false
  remote_user: developer
  become: false
  tasks:
    - name: 환경 파일 배포 - $HOME/.bashrc
      template: 
        src: templates/bashrc.j2
        dest: /home/developer/.bashrc
        owner: developer
        group: developer
        mode: '0644'

    - name: "Script Send" 
      copy: 
        src: files/99.sh
        dest: /home/developer
        owner: developer
        group: developer
        mode: '0700' 
        
    - name: "Script run" 
      ignore_errors: true 
      shell: ./99.sh

