---
- name: 0) 모듈 테스트 - lineinfile
  hosts: all, localhost
  tasks:
    - name: 1) 파일에 라인 추가
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=enforcing

