---
- name: 0) 작업 제어 실습
  hosts: webservers
  gather_facts: true
  vars_files:
    - vars/vars.yml
  tasks:
    ######################################################
    # 0) 점검 - mem > 256, 배포판: CentOS
    # 1) 패키지 설치 - httpd, mod_ssl, firewalld
    # 2) 웹 서비스 기동 - httpd
    # 3) 웹 서버 설정(notify)
    # * /etc/pki/tls/certs/localhost.crt
    # * /etc/pki/tls/private/localhost.key
    # * /var/www/html/index.html
    # 4) 방화벽 포트 등록 - http, https
    # 5) handelrs 정의
    ###########################################


    # - name: 0) 점검, (ㄱ) 메모리 점검, (ㄴ) 배포판 종류 점검
    #   ansible.builtin.fail:
    #     msg: "메모리가 256MB 보다 작거나 CentOS가 아닙니다."
    #   when: >
    #     ansible_memtotal_mb < min_ram_mb or
    #     ansible_distribution != "CentOS"

    - name: 0) 다른 점검 (ㄷ) 배포판 버전 점검
      ansible.builtin.debug:
        msg: "9일때만 된단다~~~~"
      failed_when: ansible_distribution_version != "9"
      
    - name: 1) 패키지 설치 - {{ packages }}
      dnf:
        name: "{{ packages }}"

    - name: 2) 웹 서비스 기동 - {{ services }}
      ansible.builtin.systemd:
        service: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ services }}"

    - name: block ~ rescue
      block:
        - name: 3) 웹 서버 설정
          # * /etc/pki/tls/certs/localhost.crt
          # * /etc/pki/tls/private/localhost.key
          # * /var/www/html/index.html
          ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: "{{ item.owner }}"
            group: "{{ item.group }}"
            mode: "{{ item.mode | string}}"
          loop: "{{ web_config_files }}"
          notify: restart_web_service
      rescue:
        - name: 3) 웹 서버 설정 - 에러메세지 출력
          debug:
            msg: "웹 셋팅 실패~~~~ 돌아가~~~~~"
    - name: 4) 방화벽 포트 등록 - http, https
      firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: true
        permanent: true
      loop: "{{ firewall_rules }}"
  handlers: 
    - name: restart_web_service
      systemd:
        name: "{{ web_service }}"
        state: restarted