---
- name: 0) DB 서비스 기동 - loop 테스트
  hosts: all
  gather_facts: true
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
    db_svc: mariadb
  tasks:
    - name: 2) 서비스 기동
      ansible.builtin.systemd:
        name: "{{ db_svc }}"
        state: stopped
        enabled: false

    - name: 1) 패키지 설치
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop: "{{ mariadb_packages }}"
