---
- name : Restore playbook.yml
  hosts: all
  tasks:
    - name: 방화벽 서비스 중지 및 포트 제거
      ansible.builtin.include_tasks: tasks/restore_fw.yml
      vars:
        rules:
            - http
            - https
        service: firewalld

    - name: 웹패키지 서비스 중지 및 삭제
      ansible.builtin.include_tasks: tasks/restore_web.yml
      vars:
        services: 
            - httpd
        files:
            - /var/www/html/index.html
        packages:
            - httpd
            - mod_ssl
            