---
- name: MariaDB server is installed
  hosts: databases
  remote_user: root
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_service: mariadb
    resources_url: http://ansible.example.com
    config_file_url: "{{ resources_url }}/my.cnf.standard"
    config_file_dst: /etc/my.cnf
  tasks:
    - name: set db password
      mysql_user:
        login_user: root
        login_password: soldesk1.
        name: soldesk
        password: soldesk1.
        priv: '*.*:ALL'
        state: absent

    - name: 2232323
      ansible.builtin.file:
        path: "{{ config_file_dst }}"
        state: absent
    
    - name: Make sure the database service is running
      service:
        name: "{{ db_service }}"
        state: stopped
        enabled: false

    - name: "{{ db_packages }} packages are installed"
      yum:
        name: "{{ db_packages }}"
        state: absent
        